#! /usr/bin/tcsh -f

#
# HALzap
#
# Copyright (c) 2019 Robert J. Hilderman.
# All Rights Reserved.
#

set ps_output = "`ps -u $user | grep HAL`"
@ i = 1

while ( $i <= $#ps_output )
    set line = ( $ps_output[$i] )
    if ( $line[4] == "HALstart" || $line[4] == "HAL9000" || $line[4] == "HALos" || $line[4] == "HALshell" || $line[4] == "HALkeyboardDriv" || $line[4] == "HALdisplayDrive" || $line[4] == "HALdiskDriver" || $line[4] == "HALnetworkDrive" || $line[4] == "HALfileServer" ) then
        set process_no = $line[1]
        kill -9 $process_no
    endif
    @ i ++
end    

set ps_output = "`ipcs -m -c | grep $user`"
@ i = 1

if ( $#ps_output > 0 ) then
    while ( $i <= $#ps_output )
        set line = ( $ps_output[$i] )
        set shm_id = $line[1]
        ipcrm -m $shm_id
        @ i ++
    end
endif

exit 0

